### ISSUE TITLE
test case error: error when handle incomplete genre data

### ISSUE THREAD

**Issue by lvxuntao** [The-Powerpuff-Girls3/CSC-510-Movie-Mood#3]
Among the 20 test cases, there is 1 error

### ERROR: test_create_movie_genres_incomplete_data (__main__.Tests)
**Test case 8:** Handle incomplete genre data  
----------------------------------------------------------------------  
**Traceback (most recent call last):**  
  File "D:\git\CSC-510-Movie-Mood\app\test\test_new.py", line 43, in `test_create_movie_genres_incomplete_data`  
    result = create_movie_genres(movie_genre_df)  
  File "D:\git\CSC-510-Movie-Mood\app\src\utils.py", line 87, in `create_movie_genres`  
    genres = row[1]['genres'].split('|')  
**AttributeError:** 'NoneType' object has no attribute 'split'

**Comment by lvxuntao** [comment]
This error indicates an attempt to call the split method on a None value. So we need to add a check for None values in the create_movie_genres function.

The function code should add the following check process:
        # check if genres is None
        if genres is None:
            genres = []  # If None, set empty list
        else:
            genres = genres.split('|')  # otherwise split

**Comment by lvxuntao** [comment]
The issue is solved now
